### ISSUE TITLE
Not working in csgo

### ISSUE THREAD

**Issue by RoyZ-iwnl** [Luckiris/Client-Limiter-Fix#2]

**Comment by Luckiris** [comment]
Hello,

Can you provide more information about why it is not working ?

**Comment by RoyZ-iwnl** [comment]
I have been using your plugin in the retakes server and it has been working very well. After the recent CSGO update (https://blog.counter-strike.net/index.php/2020/06/30458/), it is no longer working and allows more people to join the server through the console,and did not see any error log

Sourcemod Info
`SourceMod Version Information:
    SourceMod Version: 1.10.0.6460
    SourcePawn Engine: 1.10.0.6460, jit-x86 (build 1.10.0.6460)
    SourcePawn API: v1 = 5, v2 = 12
    Compiled on: Jan  7 2020 13:39:09
    Built from: https://github.com/alliedmodders/sourcemod/commit/2896435
    Build ID: 6460:2896435
    http://www.sourcemod.net/
`

**Comment by Luckiris** [comment]
Hello,

I tried to recompiled the plugin and everything is working on my server.

Could you try the new version I pushed ?

**Comment by RoyZ-iwnl** [comment]
Unfortunately, it didn’t work, I’ll check to see where something went wrong

**Comment by Luckiris** [comment]
Any news ?

**Comment by RoyZ-iwnl** [comment]
It's working now, thank you !
